# Generated by Django 3.2.9 on 2021-12-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Event Name')),
                ('location', models.TextField(verbose_name='Location')),
                ('time', models.DateTimeField(verbose_name='Time')),
            ],
        ),
    ]
